# Generated by Django 6.0.3 on 2026-03-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biometric_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mother_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='nik',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.CharField(),
        ),
    ]
