# Generated by Django 6.0.3 on 2026-03-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_biometric_data_alter_user_mother_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mother_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='nik',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.CharField(max_length=128),
        ),
    ]
