# Generated by Django 6.0.3 on 2026-03-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_mother_name_alter_user_nik_alter_user_pin'),
    ]

    operations = []
