# Generated by Django 6.0.3 on 2026-03-18 06:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpVerification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10)),
                ('destination', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('registration', 'Registration')], default='registration', max_length=30)),
                ('otp_code_hash', models.CharField(max_length=64)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['channel', 'destination', 'purpose'], name='user_otpver_channel_6c0aa7_idx'), models.Index(fields=['expires_at'], name='user_otpver_expires_e2c549_idx')],
            },
        ),
    ]
