# Generated by Django 6.0.3 on 2026-03-18 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationDraft',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ktp_image', models.ImageField(blank=True, null=True, upload_to='ktp_images/drafts/')),
                ('extracted_identity', models.JSONField(default=dict)),
                ('is_ktp_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp_reference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_draft', to='user.otpverification')),
            ],
            options={
                'indexes': [models.Index(fields=['is_ktp_confirmed'], name='user_regist_is_ktp__3504b0_idx')],
            },
        ),
    ]
