# Generated by Django 6.0.3 on 2026-03-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_registrationdraft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='biometric_data',
        ),
        migrations.AddField(
            model_name='user',
            name='face_embedding',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='user',
            name='face_image',
            field=models.ImageField(default='face_images/default_face.png', upload_to='face_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ktp',
            field=models.ImageField(blank=True, null=True, upload_to='ktp_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nik',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
