# Generated by Django 6.0.3 on 2026-03-29 12:25

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_registrationdraft_face_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='face_embedding',
        ),
        migrations.AddField(
            model_name='user',
            name='face_encoding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registration'), ('login', 'Login')], default='registration', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='face_image',
            field=models.ImageField(default='face_images/default_face.png', upload_to=user.models.upload_face_image_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='ktp',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.upload_ktp_image_to),
        ),
    ]
