# Generated by Django 6.0.3 on 2026-03-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_user_face_embedding_user_face_encoding_and_more'),
    ]

    operations = [
        # No-op: face_encoding field is not stored in RegistrationDraft model
    ]
