# Generated by Django 6.0.3 on 2026-04-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_registrationdraft_face_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='religion',
            field=models.CharField(choices=[('ISLAM', 'ISLAM'), ('CHRISTIANITY', 'CHRISTIANITY'), ('HINDUISM', 'HINDUISM'), ('BUDDHISM', 'BUDDHISM'), ('OTHER', 'OTHER')], max_length=50),
        ),
    ]
