# Generated by Django 6.0.3 on 2026-04-03 20:06

from django.db import migrations, models


def add_face_encoding_column_if_missing(apps, schema_editor):
    RegistrationDraft = apps.get_model('user', 'RegistrationDraft')
    table_name = RegistrationDraft._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        columns = {
            col.name
            for col in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }

    if 'face_encoding' in columns:
        return

    # JSONField is stored as TEXT on SQLite.
    quoted_table = schema_editor.quote_name(table_name)
    quoted_column = schema_editor.quote_name('face_encoding')
    schema_editor.execute(
        f"ALTER TABLE {quoted_table} ADD COLUMN {quoted_column} TEXT NULL"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_registrationdraft_face_encoding_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_face_encoding_column_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='registrationdraft',
                    name='face_encoding',
                    field=models.JSONField(blank=True, null=True),
                ),
            ],
        ),
    ]
