# Generated by Django 6.0.3 on 2026-04-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_user_nabung_ai_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biometric_login',
            field=models.BooleanField(default=False),
        ),
    ]
