# Generated by Django 6.0.3 on 2026-04-13 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0025_alter_bankaccount_id_alter_beneficiaries_id_and_more'),
        ('cs', '0002_chatmessage_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='status',
            field=models.CharField(choices=[('IDLE', 'idle'), ('ONGOING', 'ongoing'), ('DONE', 'done')], default='IDLE', max_length=20),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_number', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.bankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
