# Generated by Django 6.0.3 on 2026-03-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='status',
            field=models.CharField(choices=[('sangat_optimal', 'Sangat Optimal'), ('optimal', 'Optimal'), ('cukup_optimal', 'Cukup Optimal'), ('belum_optimal', 'Belum Optimal')], max_length=20),
        ),
    ]
