# Generated by Django 6.0.3 on 2026-03-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_alter_cashflow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='block',
            field=models.BooleanField(default=False),
        ),
    ]
