# Generated by Django 6.0.3 on 2026-04-01 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_bankaccount_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=6)),
                ('ccv', models.CharField(max_length=4)),
                ('block_permanent', models.BooleanField(default=False)),
                ('block_temporary', models.BooleanField(default=False)),
                ('daily_transaction_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('daily_withdrawal_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('expiry_date', models.DateField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_details', to='banking.bankaccount')),
            ],
        ),
    ]
