# Generated by Django 6.0.3 on 2026-04-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_carddetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddetails',
            name='daily_single_transaction_limit',
            field=models.IntegerField(default=50000000),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='daily_transaction_limit',
            field=models.IntegerField(default=100000000),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='daily_withdrawal_limit',
            field=models.IntegerField(default=15000000),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='total_expense',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='total_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after',
            field=models.IntegerField(),
        ),
    ]
