# Generated by Django 6.0.3 on 2026-04-01 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_carddetails_daily_single_transaction_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saku',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('saku_name', models.CharField(max_length=50)),
                ('category_name', models.CharField(choices=[('Nabung', 'Nabung'), ('Transaksi', 'Transaksi'), ('Lainnya', 'Lainnya')], max_length=50)),
                ('balance', models.IntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SakuDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='cashflow',
            constraint=models.UniqueConstraint(fields=('account_id', 'month', 'year'), name='unique_cashflow_per_account_month_year'),
        ),
        migrations.AddField(
            model_name='saku',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sakus', to='banking.bankaccount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='saku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.saku'),
        ),
        migrations.AddField(
            model_name='sakudetails',
            name='saku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='banking.saku'),
        ),
        migrations.AddConstraint(
            model_name='saku',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('account',), name='unique_primary_saku_per_account'),
        ),
    ]
