# Generated by Django 6.0.3 on 2026-04-03 20:06

import uuid
from django.db import migrations, models


def populate_transaction_uuid(apps, schema_editor):
    Transaction = apps.get_model('banking', 'Transaction')
    for tx in Transaction.objects.filter(transaction_id__isnull=True).iterator():
        tx.transaction_id = uuid.uuid4()
        tx.save(update_fields=['transaction_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_merge_transaction_category_into_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='qris',
            name='PAN_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='qris',
            name='aquirer',
            field=models.CharField(blank=True, choices=[('Bank BCA', 'Bank BCA')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qris',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.RunPython(populate_transaction_uuid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='saku',
            name='category_name',
            field=models.CharField(choices=[('nabung', 'Nabung'), ('transaksi', 'Transaksi'), ('lainnya', 'Lainnya')], max_length=50),
        ),
    ]
