# Generated by Django 6.0.3 on 2026-04-04 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_qris_pan_id_qris_aquirer_qris_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='merchant_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='qris',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='banking.qris'),
        ),
    ]
