# Generated by Django 6.0.3 on 2026-04-04 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_transaction_merchant_name_snapshot_transaction_qris_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saku',
            name='category_name',
            field=models.CharField(choices=[('nabung', 'Nabung'), ('transaksi', 'Transaksi'), ('celengan', 'Celengan'), ('lainnya', 'Lainnya')], max_length=50),
        ),
        migrations.CreateModel(
            name='Beneficiaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(default='IKE Bank', max_length=255)),
                ('account_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='banking.bankaccount')),
                ('destination_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_beneficiary_destination', to='banking.bankaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['account_id', 'added_at'], name='banking_ben_account_101bcf_idx')],
                'constraints': [models.UniqueConstraint(fields=('account_id', 'account_number'), name='unique_beneficiary_per_account_number')],
            },
        ),
    ]
