# Generated by Django 6.0.3 on 2026-04-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0010_alter_saku_category_name_beneficiaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddetails',
            name='card_status',
            field=models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('delivered', 'Delivered'), ('requested', 'Requested'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
