# Generated by Django 6.0.3 on 2026-04-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0011_carddetails_card_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiaries',
            name='alias',
        ),
        migrations.AlterField(
            model_name='saku',
            name='category_name',
            field=models.CharField(choices=[('utama', 'Utama'), ('nabung', 'Nabung'), ('transaksi', 'Transaksi'), ('celengan', 'Celengan'), ('lainnya', 'Lainnya')], max_length=50),
        ),
    ]
