# Generated by Django 6.0.3 on 2026-04-05 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0012_remove_beneficiaries_alias_alter_saku_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddetails',
            name='account_id',
        ),
        migrations.AddField(
            model_name='carddetails',
            name='card_number',
            field=models.OneToOneField(blank=True, db_column='card_number', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_details', to='banking.bankaccount', to_field='card_number'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
