# Generated by Django 6.0.3 on 2026-04-05

from django.db import migrations, models
import django.db.models.deletion


def copy_carddetails_account(apps, schema_editor):
    CardDetails = apps.get_model('banking', 'CardDetails')

    for row in CardDetails.objects.select_related('card_number').all():
        bank_account = getattr(row, 'card_number', None)
        if bank_account is None:
            continue

        row.account = bank_account
        row.save(update_fields=['account'])


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0013_remove_carddetails_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddetails',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_details_history', to='banking.bankaccount'),
        ),
        migrations.RunPython(copy_carddetails_account, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='carddetails',
            name='card_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
