# Generated by Django 6.0.3 on 2026-04-06 17:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0015_carddetails_added_at_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('deposito_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('interest_rate', models.FloatField()),
                ('quota', models.IntegerField(null=True)),
                ('duratuion_months', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='card_status',
            field=models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('requested', 'Requested'), ('none', 'None')], default='none', max_length=20),
        ),
        migrations.CreateModel(
            name='DepositoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposito_account_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('balance', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('deposito_name', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_depositos', to='banking.bankaccount')),
            ],
        ),
    ]
