# Generated by Django 6.0.3 on 2026-04-06 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0016_deposito_alter_carddetails_card_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositoaccount',
            old_name='account',
            new_name='account_id',
        ),
        migrations.AddField(
            model_name='depositoaccount',
            name='deposito_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_depositos', to='banking.deposito'),
        ),
    ]
