# Generated by Django 6.0.3 on 2026-04-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0017_rename_account_depositoaccount_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposito',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='depositoaccount',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn')], default='active', max_length=20),
        ),
    ]
