# Generated by Django 6.0.3 on 2026-04-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0018_deposito_status_depositoaccount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposito',
            name='isSpecial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deposito',
            name='quota',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
