# Generated by Django 6.0.3 on 2026-04-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0019_deposito_isspecial_alter_deposito_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddetails',
            name='source_funds_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
