# Generated by Django 6.0.3 on 2026-04-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0021_cardblacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetails',
            name='card_status',
            field=models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('requested', 'Requested'), ('blocked_temporary', 'Blocked Temporary'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
