# Generated by Django 6.0.3 on 2026-04-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0025_alter_bankaccount_id_alter_beneficiaries_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='hacked',
            field=models.BooleanField(default=False),
        ),
    ]
