# Generated by Django 6.0.3 on 2026-04-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0026_bankaccount_hacked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='hacked',
        ),
    ]
