# Generated by Django 6.0.3 on 2026-04-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0027_remove_bankaccount_hacked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='card_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
