# Generated by Django 5.2.7 on 2026-04-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0028_alter_bankaccount_id_alter_beneficiaries_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='card_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
