# Generated by Django 5.2.7 on 2026-04-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0028_alter_bankaccount_card_number'),
        ('banking', '0029_alter_bankaccount_card_number'),
    ]

    operations = [
    ]
