# Generated by Django 6.0.3 on 2026-04-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0028_alter_bankaccount_card_number'),
        ('banking', '0029_alter_bankaccount_card_number'),
    ]

    operations = [
    ]
