# Generated by Django 5.2.7 on 2026-04-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0030_merge_20260414_2105'),
        ('banking', '0031_alter_bankaccount_id_alter_beneficiaries_id_and_more'),
    ]

    operations = [
    ]
